(begin
  (define (caaaar pair) (car (caaar pair)))
  (define (caaadr pair) (car (caadr pair)))
  (define (caaar pair) (car (caar pair)))
  (define (caadar pair) (car (cadar pair)))
  (define (caaddr pair) (car (caddr pair)))
  (define (caadr pair) (car (cadr pair)))
  (define (cadaar pair) (car (cdaar pair)))
  (define (cadadr pair) (car (cdadr pair)))
  (define (cadar pair) (car (cdar pair)))
  (define (caddar pair) (car (cddar pair)))
  (define (cadddr pair) (car (cdddr pair)))
  (define (caddr pair) (car (cddr pair)))
  (define (cdaaar pair) (cdr (caaar pair)))
  (define (cdaadr pair) (cdr (caadr pair)))
  (define (cdaar pair) (cdr (caar pair)))
  (define (cdadar pair) (cdr (cadar pair)))
  (define (cdaddr pair) (cdr (caddr pair)))
  (define (cdadr pair) (cdr (cadr pair)))
  (define (cddaar pair) (cdr (cdaar pair)))
  (define (cddadr pair) (cdr (cdadr pair)))
  (define (cddar pair) (cdr (cdar pair)))
  (define (cdddar pair) (cdr (cddar pair)))
  (define (cddddr pair) (cdr (cdddr pair)))
  (define (cdddr pair) (cdr (cddr pair)))
  'cxr-library
  )
