
#line 3 "lex.yy.c"

#define YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN (-32767 - 1)
#endif
#ifndef INT32_MIN
#define INT32_MIN (-2147483647 - 1)
#endif
#ifndef INT8_MAX
#define INT8_MAX (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else /* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined(__STDC__)

#define YY_USE_CONST

#endif /* defined (__STDC__) */
#endif /* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int)(unsigned char)c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start)-1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin)

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the
 * main buffer.
 */
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n)                                                              \
  do {                                                                         \
    /* Undo effects of setting up yytext. */                                   \
    int yyless_macro_arg = (n);                                                \
    YY_LESS_LINENO(yyless_macro_arg);                                          \
    *yy_cp = (yy_hold_char);                                                   \
    YY_RESTORE_YY_MORE_OFFSET(yy_c_buf_p) = yy_cp =                            \
        yy_bp + yyless_macro_arg - YY_MORE_ADJ;                                \
    YY_DO_BEFORE_ACTION; /* set up yytext again */                             \
  } while (0)

#define unput(c) yyunput(c, (yytext_ptr))

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state {
  FILE *yy_input_file;

  char *yy_ch_buf;  /* input buffer */
  char *yy_buf_pos; /* current position in input buffer */

  /* Size of input buffer in bytes, not including room for EOB
   * characters.
   */
  yy_size_t yy_buf_size;

  /* Number of characters read into yy_ch_buf, not including EOB
   * characters.
   */
  yy_size_t yy_n_chars;

  /* Whether we "own" the buffer - i.e., we know we created it,
   * and can realloc() it to grow it, and should free() it to
   * delete it.
   */
  int yy_is_our_buffer;

  /* Whether this is an "interactive" input source; if so, and
   * if we're using stdio for input, then we want to use getc()
   * instead of fread(), to make sure we stop fetching input after
   * each newline.
   */
  int yy_is_interactive;

  /* Whether we're considered to be at the beginning of a line.
   * If so, '^' rules will be active on the next match, otherwise
   * not.
   */
  int yy_at_bol;

  int yy_bs_lineno; /**< The line count. */
  int yy_bs_column; /**< The column count. */

  /* Whether to try to fill the input buffer when we reach the
   * end of it.
   */
  int yy_fill_buffer;

  int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
/* When an EOF's been seen but there's still some text to process
 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
 * shouldn't try reading from the input source any more.  We might
 * still have a bunch of tokens to match, though, because of
 * possible backing-up.
 *
 * When we actually see the EOF, we change the status to "new"
 * (via yyrestart()), so that the user can continue scanning by
 * just pointing yyin at a new input file.
 */
#define YY_BUFFER_EOF_PENDING 2
};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0;       /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0;       /**< capacity of stack. */
static YY_BUFFER_STATE *yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER                                                      \
  ((yy_buffer_stack) ? (yy_buffer_stack)[(yy_buffer_stack_top)] : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars; /* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *)0;
static int yy_init = 0;  /* whether we need to initialize */
static int yy_start = 0; /* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart(FILE *input_file);
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer);
YY_BUFFER_STATE yy_create_buffer(FILE *file, int size);
void yy_delete_buffer(YY_BUFFER_STATE b);
void yy_flush_buffer(YY_BUFFER_STATE b);
void yypush_buffer_state(YY_BUFFER_STATE new_buffer);
void yypop_buffer_state(void);

static void yyensure_buffer_stack(void);
static void yy_load_buffer_state(void);
static void yy_init_buffer(YY_BUFFER_STATE b, FILE *file);

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER)

YY_BUFFER_STATE yy_scan_buffer(char *base, yy_size_t size);
YY_BUFFER_STATE yy_scan_string(yyconst char *yy_str);
YY_BUFFER_STATE yy_scan_bytes(yyconst char *bytes, yy_size_t len);

void *yyalloc(yy_size_t);
void *yyrealloc(void *, yy_size_t);
void yyfree(void *);

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive)                                     \
  {                                                                            \
    if (!YY_CURRENT_BUFFER) {                                                  \
      yyensure_buffer_stack();                                                 \
      YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);          \
    }                                                                          \
    YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive;              \
  }

#define yy_set_bol(at_bol)                                                     \
  {                                                                            \
    if (!YY_CURRENT_BUFFER) {                                                  \
      yyensure_buffer_stack();                                                 \
      YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);          \
    }                                                                          \
    YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol;                              \
  }

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/ 1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *)0, *yyout = (FILE *)0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state(void);
static yy_state_type yy_try_NUL_trans(yy_state_type current_state);
static int yy_get_next_buffer(void);
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void
yy_fatal_error(yyconst char msg[]);

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION                                                    \
  (yytext_ptr) = yy_bp;                                                        \
  yyleng = (size_t)(yy_cp - yy_bp);                                            \
  (yy_hold_char) = *yy_cp;                                                     \
  *yy_cp = '\0';                                                               \
  (yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info {
  flex_int32_t yy_verify;
  flex_int32_t yy_nxt;
};
static yyconst flex_int16_t yy_accept[330] = {
    0,  2,  2,  0,  0,  0,  0,  54, 52, 2,  1,  1,  12, 30, 52, 8,  6,
    7,  14, 14, 9,  12, 44, 52, 52, 52, 52, 52, 31, 41, 53, 31, 31, 31,
    53, 51, 46, 46, 46, 46, 2,  2,  1,  12, 0,  0,  0,  10, 5,  18, 17,
    0,  42, 44, 43, 0,  45, 0,  14, 14, 0,  0,  0,  0,  14, 44, 0,  0,
    0,  0,  0,  12, 0,  0,  3,  3,  0,  0,  0,  0,  0,  15, 0,  0,  0,
    12, 0,  0,  0,  39, 39, 37, 0,  38, 32, 33, 35, 36, 34, 31, 0,

    0,  47, 47, 47, 47, 2,  0,  0,  0,  0,  19, 19, 19, 19, 19, 19, 19,
    19, 19, 19, 0,  0,  0,  42, 0,  42, 44, 43, 0,  43, 0,  45, 0,  45,
    0,  0,  14, 14, 0,  0,  0,  14, 14, 0,  0,  0,  0,  0,  14, 14, 14,
    0,  0,  0,  0,  0,  12, 44, 3,  16, 0,  0,  0,  0,  13, 0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    39, 0,  0,  48, 49, 50, 0,  0,  0,  0,  0,  0,  0,  0,  0,

    0,  0,  0,  29, 0,  0,  42, 43, 11, 45, 4,  0,  0,  14, 14, 0,  0,
    0,  0,  0,  0,  14, 0,  0,  0,  0,  44, 0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  40, 0,  17, 0,  0,  0,  0,  0,  0,  0,  0,  28,
    0,  42, 43, 45, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  18, 0,  0,  0,  0,

    0,  25, 0,  0,  0,  0,  0,  0,  0,  0,  0,  20, 0,  0,  0,  0,  0,
    27, 0,  0,  22, 23, 0,  26, 0,  24, 0,  21, 0};

static yyconst YY_CHAR yy_ec[256] = {
    0,  1,  1,  1,  1,  1,  1,  1,  1,  2,  3,  1,  1,  4,  1,  1,  1,  1,  1,
    1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  5,  6,  7,  5,  5,
    5,  8,  9,  10, 5,  11, 1,  12, 13, 14, 15, 16, 17, 18, 18, 19, 20, 20, 21,
    22, 5,  23, 5,  5,  5,  5,  24, 25, 26, 26, 26, 27, 28, 5,  5,  5,  5,  5,
    29, 5,  5,  5,  5,  5,  30, 31, 32, 33, 5,  5,  34, 5,  5,  1,  35, 1,  5,
    5,  1,  36, 37, 38, 39,

    40, 28, 5,  5,  41, 5,  42, 43, 44, 45, 46, 47, 5,  48, 49, 50, 51, 5,  52,
    53, 5,  5,  1,  54, 1,  5,  1,  55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
    55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 56, 56, 57, 57,
    57, 57, 57, 57, 57,

    57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57,
    57, 57, 57, 57, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58,
    58, 59, 59, 59, 59, 59, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56};

static yyconst YY_CHAR yy_meta[60] = {
    0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 2, 4, 5, 6, 6, 6, 6,
    6, 6, 6, 1, 2, 7, 7, 7, 7, 2, 2, 2, 2, 2, 2, 1, 7, 7, 7, 7,
    7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 8, 8, 2, 2, 2};

static yyconst flex_uint16_t yy_base[354] = {
    0,    0,    0,    54,   57,   107,  120,  1025, 1585, 62,   65,   68,
    16,   1585, 134,  1585, 1585, 1585, 74,   178,  50,   222,  1010, 73,
    281,  968,  967,  961,  1585, 1585, 339,  942,  941,  939,  1585, 1585,
    1585, 78,   129,  186,  76,   79,   99,   47,   938,  937,  936,  1585,
    1585, 85,   104,  357,  144,  76,   197,  969,  106,  926,  207,  210,
    167,  855,  854,  853,  406,  890,  341,  420,  848,  843,  827,  230,
    237,  150,  1585, 160,  309,  479,  538,  597,  400,  1585, 323,  403,
    412,  117,  824,  823,  179,  874,  165,  1585, 0,    1585, 1585, 1585,
    1585, 1585, 1585, 1585, 820,

    807,  255,  475,  331,  1585, 225,  796,  795,  143,  227,  1585, 806,
    809,  790,  780,  311,  785,  776,  784,  0,    764,  759,  758,  247,
    787,  341,  778,  489,  423,  501,  782,  218,  0,    347,  736,  357,
    646,  649,  731,  728,  726,  652,  655,  722,  718,  717,  706,  705,
    507,  746,  745,  702,  697,  681,  678,  677,  665,  673,  1585, 1585,
    642,  663,  680,  739,  1585, 696,  709,  721,  798,  857,  916,  730,
    777,  783,  975,  1034, 789,  836,  842,  0,    848,  0,    954,  960,
    675,  727,  696,  661,  1585, 1585, 1585, 647,  339,  345,  642,  637,
    631,  634,  619,  626,

    482,  495,  493,  0,    458,  457,  375,  708,  1585, 0,    457,  455,
    446,  758,  815,  445,  444,  443,  429,  421,  420,  985,  1009, 419,
    418,  417,  1033, 1021, 1027, 1041, 0,    1048, 1059, 0,    0,    1066,
    1073, 1080, 1139, 1198, 1101, 1118, 1126, 0,    1132, 1177, 1190, 1204,
    1183, 1210, 1216, 0,    1224, 1231, 445,  1237, 1585, 368,  1585, 411,
    414,  415,  416,  408,  406,  395,  397,  1585, 374,  388,  869,  0,
    366,  365,  358,  357,  354,  1245, 1252, 0,    1258, 1266, 0,    0,
    1273, 1279, 1287, 0,    1294, 1300, 1308, 1326, 1315, 1333, 1340, 1585,
    357,  337,  333,  332,

    330,  1585, 321,  320,  178,  1346, 0,    1354, 1361, 1367, 1375, 1585,
    163,  137,  130,  120,  116,  1585, 1382, 119,  1585, 1585, 79,   1585,
    53,   1585, 44,   1585, 1585, 1441, 1449, 1456, 1462, 1468, 1472, 1478,
    1486, 1491, 1498, 1505, 1511, 1517, 1524, 1532, 1536, 1539, 1541, 1547,
    1554, 1562, 1566, 1569, 1576};

static yyconst flex_int16_t yy_def[354] = {
    0,   329, 1,   330, 330, 331, 331, 329, 329, 329, 329, 329, 332, 329, 329,
    329, 329, 329, 333, 333, 334, 332, 335, 336, 329, 329, 329, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 332, 329,
    329, 329, 329, 329, 329, 329, 337, 329, 335, 329, 329, 338, 339, 340, 340,
    341, 329, 329, 329, 340, 335, 342, 342, 329, 329, 329, 21,  329, 336, 329,
    336, 343, 344, 329, 329, 329, 329, 343, 343, 343, 332, 329, 329, 329, 329,
    329, 329, 345, 329, 329, 329, 329, 329, 329, 329, 329,

    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329,
    329, 329, 329, 329, 346, 329, 329, 329, 329, 329, 329, 335, 329, 329, 329,
    329, 338, 347, 338, 339, 339, 340, 340, 329, 329, 329, 348, 348, 329, 329,
    329, 329, 329, 64,  329, 329, 329, 329, 329, 329, 329, 21,  329, 329, 329,
    343, 343, 343, 344, 329, 343, 343, 343, 349, 349, 329, 343, 343, 343, 350,
    350, 343, 343, 343, 351, 343, 164, 343, 343, 329, 329, 345, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329,

    329, 329, 329, 346, 329, 329, 329, 329, 329, 352, 339, 329, 329, 348, 348,
    329, 329, 329, 329, 329, 329, 64,  334, 329, 329, 329, 329, 343, 343, 343,
    164, 343, 343, 170, 170, 343, 343, 343, 353, 353, 343, 343, 343, 170, 343,
    343, 343, 343, 343, 343, 343, 176, 343, 343, 351, 343, 329, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 352, 329, 329, 329,
    329, 329, 343, 343, 170, 343, 343, 240, 240, 343, 343, 343, 240, 343, 343,
    343, 343, 343, 343, 343, 329, 329, 329, 329, 329,

    329, 329, 329, 329, 329, 343, 240, 343, 343, 343, 343, 329, 329, 329, 329,
    329, 329, 329, 343, 329, 329, 329, 329, 329, 329, 329, 329, 329, 0,   329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329};

static yyconst flex_uint16_t yy_nxt[1645] = {
    0,   8,   9,   10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,
    22,  22,  22,  22,  22,  22,  22,  22,  23,  8,   12,  12,  12,  12,  12,
    12,  12,  12,  12,  12,  8,   12,  12,  12,  12,  12,  12,  12,  12,  12,
    12,  12,  12,  12,  12,  12,  12,  12,  12,  24,  8,   8,   25,  26,  27,
    29,  67,  67,  29,  40,  40,  41,  40,  40,  41,  40,  42,  41,  44,  45,
    46,  74,  75,  40,  40,  41,  40,  106, 41,  328, 59,  59,  60,  127, 30,
    72,  327, 30,  102, 102, 102, 102, 102, 102, 102, 102,

    40,  40,  41,  44,  45,  46,  68,  69,  70,  109, 31,  32,  33,  31,  32,
    33,  35,  132, 326, 133, 109, 36,  37,  38,  39,  39,  39,  39,  39,  35,
    61,  62,  63,  110, 36,  37,  38,  39,  39,  39,  39,  39,  47,  103, 103,
    103, 103, 104, 105, 105, 105, 110, 74,  75,  325, 124, 48,  125, 126, 126,
    324, 49,  159, 75,  323, 50,  186, 89,  51,  322, 52,  193, 53,  44,  45,
    46,  321, 143, 143, 54,  88,  89,  90,  50,  55,  193, 56,  57,  59,  59,
    60,  64,  65,  65,  65,  65,  65,  65,  65,  65,

    105, 105, 105, 105, 105, 105, 105, 105, 128, 320, 129, 130, 130, 130, 130,
    130, 130, 138, 138, 138, 138, 138, 138, 144, 145, 146, 40,  40,  41,  329,
    138, 133, 214, 138, 61,  62,  63,  71,  71,  71,  71,  71,  71,  71,  157,
    157, 157, 157, 157, 157, 157, 157, 158, 158, 158, 158, 158, 158, 158, 194,
    125, 126, 126, 139, 140, 141, 139, 140, 141, 189, 189, 189, 189, 189, 189,
    189, 189, 194, 44,  45,  46,  76,  76,  76,  76,  77,  76,  76,  76,  76,
    76,  78,  78,  79,  77,  76,  76,  76,  76,  76,

    76,  76,  76,  76,  76,  77,  77,  77,  77,  77,  77,  77,  77,  77,  77,
    80,  77,  77,  77,  77,  77,  77,  77,  77,  77,  77,  77,  77,  77,  77,
    77,  77,  77,  77,  81,  76,  76,  82,  83,  84,  88,  89,  90,  80,  91,
    191, 191, 191, 191, 191, 199, 151, 151, 151, 125, 126, 126, 80,  329, 318,
    133, 200, 160, 211, 151, 161, 162, 163, 317, 258, 316, 259, 92,  93,  94,
    95,  160, 182, 315, 161, 162, 163, 314, 96,  259, 313, 97,  258, 98,  270,
    270, 92,  112, 113, 296, 114, 115, 152, 153, 154,

    312, 116, 270, 270, 117, 118, 119, 296, 150, 120, 136, 142, 305, 121, 122,
    123, 138, 138, 138, 214, 137, 149, 149, 149, 149, 149, 149, 149, 111, 138,
    151, 151, 151, 180, 304, 181, 181, 80,  208, 208, 208, 208, 208, 151, 181,
    303, 80,  181, 302, 181, 301, 300, 180, 76,  299, 298, 160, 183, 297, 161,
    162, 163, 139, 140, 141, 160, 184, 76,  161, 162, 163, 66,  277, 150, 58,
    276, 152, 153, 154, 76,  76,  76,  76,  142, 76,  76,  76,  76,  76,  190,
    190, 190, 190, 190, 190, 190, 190, 275, 274, 214,

    273, 76,  129, 130, 130, 130, 130, 130, 130, 137, 136, 269, 111, 80,  129,
    130, 130, 130, 130, 130, 130, 222, 222, 222, 222, 222, 222, 222, 222, 268,
    267, 266, 165, 76,  76,  166, 167, 168, 76,  76,  76,  76,  169, 76,  76,
    76,  76,  76,  170, 170, 171, 169, 76,  76,  76,  76,  76,  76,  76,  76,
    76,  169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 80,  169, 169,
    169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 169,
    169, 81,  76,  76,  172, 173, 174, 76,  76,  76,

    76,  175, 76,  76,  76,  76,  76,  176, 176, 175, 175, 76,  76,  76,  76,
    76,  76,  76,  76,  76,  175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
    175, 80,  175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
    175, 175, 175, 175, 175, 160, 76,  76,  177, 178, 179, 138, 138, 138, 138,
    138, 138, 215, 215, 215, 215, 215, 215, 265, 138, 264, 263, 138, 262, 261,
    215, 80,  260, 215, 157, 157, 157, 157, 157, 157, 157, 157, 227, 227, 227,
    227, 227, 227, 227, 227, 160, 228, 80,  161, 162,

    163, 43,  139, 140, 141, 139, 140, 141, 216, 217, 218, 216, 217, 218, 80,
    99,  160, 229, 257, 161, 162, 163, 271, 271, 271, 271, 271, 271, 186, 85,
    80,  226, 66,  160, 230, 225, 161, 162, 163, 76,  76,  76,  76,  80,  76,
    76,  76,  76,  76,  160, 231, 224, 161, 162, 163, 80,  150, 223, 223, 221,
    58,  76,  160, 232, 80,  161, 162, 163, 215, 215, 215, 220, 219, 80,  160,
    233, 142, 161, 162, 163, 213, 215, 212, 160, 244, 137, 161, 162, 163, 136,
    209, 72,  165, 76,  76,  166, 167, 168, 76,  76,

    76,  76,  207, 76,  76,  76,  76,  76,  235, 235, 235, 80,  206, 205, 216,
    217, 218, 80,  111, 203, 76,  235, 202, 80,  201, 215, 215, 215, 198, 197,
    160, 245, 80,  161, 162, 163, 160, 246, 215, 161, 162, 163, 160, 252, 196,
    161, 162, 163, 195, 192, 43,  81,  76,  76,  236, 237, 238, 76,  76,  76,
    76,  188, 76,  76,  76,  76,  76,  235, 235, 235, 80,  216, 217, 218, 99,
    186, 80,  185, 85,  76,  235, 156, 80,  271, 271, 271, 271, 271, 271, 160,
    253, 80,  161, 162, 163, 160, 254, 155, 161, 162,

    163, 160, 66,  72,  161, 162, 163, 148, 147, 58,  81,  76,  76,  236, 237,
    238, 76,  76,  76,  76,  239, 76,  76,  76,  76,  76,  240, 240, 239, 239,
    76,  76,  76,  76,  76,  76,  76,  76,  76,  239, 239, 239, 239, 239, 239,
    239, 239, 239, 239, 239, 80,  239, 239, 239, 239, 239, 239, 239, 239, 239,
    239, 239, 239, 239, 239, 239, 239, 239, 239, 160, 76,  76,  241, 242, 243,
    76,  76,  76,  76,  136, 76,  76,  76,  76,  76,  248, 248, 248, 80,  131,
    108, 107, 43,  101, 80,  100, 99,  76,  248, 222,

    222, 222, 222, 222, 222, 222, 222, 160, 182, 80,  161, 162, 163, 160, 256,
    87,  161, 162, 163, 67,  67,  86,  85,  72,  329, 329, 329, 329, 160, 76,
    76,  249, 250, 251, 76,  76,  76,  76,  329, 76,  76,  76,  76,  76,  248,
    248, 248, 227, 227, 227, 227, 227, 227, 227, 227, 80,  76,  248, 329, 329,
    329, 80,  329, 329, 329, 68,  69,  70,  80,  329, 329, 329, 329, 329, 160,
    80,  329, 161, 162, 163, 160, 228, 80,  161, 162, 163, 329, 160, 76,  76,
    249, 250, 251, 80,  160, 278, 329, 161, 162, 163,

    80,  160, 231, 329, 161, 162, 163, 80,  329, 329, 329, 329, 160, 279, 80,
    161, 162, 163, 329, 160, 280, 329, 161, 162, 163, 329, 160, 281, 329, 161,
    162, 163, 329, 160, 282, 80,  161, 162, 163, 76,  76,  76,  76,  329, 76,
    76,  76,  76,  76,  284, 284, 284, 80,  329, 160, 288, 329, 161, 162, 163,
    80,  76,  284, 329, 329, 329, 80,  329, 329, 329, 329, 160, 289, 80,  161,
    162, 163, 329, 329, 160, 290, 329, 161, 162, 163, 160, 244, 329, 161, 162,
    163, 329, 81,  76,  76,  285, 286, 287, 76,  76,

    76,  76,  79,  76,  76,  76,  76,  76,  284, 284, 284, 80,  329, 329, 329,
    329, 79,  80,  329, 329, 76,  284, 329, 329, 80,  329, 329, 329, 329, 329,
    160, 291, 80,  161, 162, 163, 160, 292, 80,  161, 162, 163, 329, 81,  80,
    329, 161, 162, 163, 329, 80,  81,  76,  76,  285, 286, 287, 81,  80,  329,
    161, 162, 163, 160, 293, 80,  161, 162, 163, 160, 294, 80,  161, 162, 163,
    329, 329, 160, 252, 80,  161, 162, 163, 329, 160, 295, 80,  161, 162, 163,
    160, 182, 80,  161, 162, 163, 329, 329, 160, 228,

    80,  161, 162, 163, 329, 160, 231, 80,  161, 162, 163, 160, 280, 80,  161,
    162, 163, 329, 329, 160, 306, 80,  161, 162, 163, 329, 160, 307, 80,  161,
    162, 163, 160, 308, 80,  161, 162, 163, 79,  329, 160, 309, 80,  161, 162,
    163, 329, 160, 288, 80,  161, 162, 163, 160, 310, 329, 161, 162, 163, 329,
    80,  160, 244, 329, 161, 162, 163, 80,  160, 292, 329, 161, 162, 163, 80,
    329, 329, 329, 329, 81,  80,  329, 161, 162, 163, 329, 160, 311, 80,  161,
    162, 163, 329, 160, 252, 80,  161, 162, 163, 160,

    280, 80,  161, 162, 163, 329, 329, 160, 307, 80,  161, 162, 163, 329, 160,
    319, 80,  161, 162, 163, 160, 288, 329, 161, 162, 163, 329, 329, 160, 292,
    329, 161, 162, 163, 329, 160, 307, 329, 161, 162, 163, 28,  28,  28,  28,
    28,  28,  28,  28,  34,  34,  34,  34,  34,  34,  34,  34,  43,  43,  43,
    43,  43,  43,  58,  58,  58,  329, 329, 58,  66,  66,  66,  329, 329, 66,
    65,  65,  65,  73,  73,  73,  73,  73,  73,  73,  73,  111, 111, 111, 111,
    111, 111, 111, 134, 134, 134, 134, 134, 135, 135,

    135, 135, 135, 135, 135, 135, 137, 137, 137, 137, 137, 137, 142, 142, 142,
    329, 329, 142, 150, 150, 150, 150, 150, 150, 76,  76,  76,  76,  76,  76,
    76,  76,  164, 164, 164, 164, 164, 164, 164, 164, 187, 187, 187, 204, 204,
    204, 210, 210, 214, 214, 214, 214, 214, 214, 234, 234, 234, 234, 234, 234,
    234, 234, 247, 247, 247, 247, 247, 247, 247, 247, 255, 255, 255, 272, 272,
    272, 283, 283, 283, 283, 283, 283, 283, 283, 7,   329, 329, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329,

    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329};

static yyconst flex_int16_t yy_chk[1645] = {
    0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
    1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
    1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
    1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
    3,   20,  20,  4,   9,   9,   9,   10,  10,  10,  11,  11,  11,  12,  12,
    12,  23,  23,  40,  40,  40,  41,  41,  41,  327, 18,  18,  18,  53,  3,
    53,  325, 4,   37,  37,  37,  37,  37,  37,  37,  37,

    42,  42,  42,  43,  43,  43,  20,  20,  20,  49,  3,   3,   3,   4,   4,
    4,   5,   56,  323, 56,  49,  5,   5,   5,   5,   5,   5,   5,   5,   6,
    18,  18,  18,  50,  6,   6,   6,   6,   6,   6,   6,   6,   14,  38,  38,
    38,  38,  38,  38,  38,  38,  50,  73,  73,  320, 52,  14,  52,  52,  52,
    317, 14,  75,  75,  316, 14,  90,  90,  14,  315, 14,  109, 14,  85,  85,
    85,  314, 60,  60,  14,  88,  88,  88,  14,  14,  109, 14,  14,  19,  19,
    19,  19,  19,  19,  19,  19,  19,  19,  19,  19,

    39,  39,  39,  39,  39,  39,  39,  39,  54,  313, 54,  54,  54,  54,  54,
    54,  54,  58,  58,  58,  59,  59,  59,  60,  60,  60,  106, 106, 106, 132,
    58,  132, 305, 59,  19,  19,  19,  21,  21,  21,  21,  21,  21,  21,  71,
    71,  71,  71,  71,  71,  71,  71,  72,  72,  72,  72,  72,  72,  72,  110,
    124, 124, 124, 58,  58,  58,  59,  59,  59,  102, 102, 102, 102, 102, 102,
    102, 102, 110, 21,  21,  21,  24,  24,  24,  24,  24,  24,  24,  24,  24,
    24,  24,  24,  24,  24,  24,  24,  24,  24,  24,

    24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,
    24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  24,
    24,  24,  24,  24,  24,  24,  24,  24,  24,  24,  30,  30,  30,  76,  30,
    104, 104, 104, 104, 104, 116, 66,  66,  66,  126, 126, 126, 82,  134, 304,
    134, 116, 76,  136, 66,  76,  76,  76,  303, 193, 301, 194, 30,  30,  30,
    30,  82,  82,  300, 82,  82,  82,  299, 30,  194, 298, 30,  193, 30,  207,
    207, 30,  51,  51,  258, 51,  51,  66,  66,  66,

    297, 51,  270, 270, 51,  51,  51,  258, 277, 51,  136, 276, 275, 51,  51,
    51,  64,  64,  64,  274, 273, 64,  64,  64,  64,  64,  64,  64,  269, 64,
    67,  67,  67,  80,  267, 80,  80,  83,  129, 129, 129, 129, 129, 67,  80,
    266, 84,  80,  265, 80,  264, 263, 80,  80,  262, 261, 83,  83,  260, 83,
    83,  83,  64,  64,  64,  84,  84,  255, 84,  84,  84,  226, 225, 224, 221,
    220, 67,  67,  67,  77,  77,  77,  77,  219, 77,  77,  77,  77,  77,  103,
    103, 103, 103, 103, 103, 103, 103, 218, 217, 216,

    213, 77,  128, 128, 128, 128, 128, 128, 128, 212, 211, 206, 205, 77,  130,
    130, 130, 130, 130, 130, 130, 149, 149, 149, 149, 149, 149, 149, 149, 203,
    202, 201, 77,  77,  77,  77,  77,  77,  78,  78,  78,  78,  78,  78,  78,
    78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,
    78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,
    78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,  78,
    78,  78,  78,  78,  78,  78,  78,  79,  79,  79,

    79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,
    79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,
    79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,
    79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  79,  137, 137, 137, 138,
    138, 138, 142, 142, 142, 143, 143, 143, 200, 137, 199, 198, 138, 197, 196,
    142, 161, 195, 143, 157, 157, 157, 157, 157, 157, 157, 157, 158, 158, 158,
    158, 158, 158, 158, 158, 161, 161, 162, 161, 161,

    161, 192, 137, 137, 137, 138, 138, 138, 142, 142, 142, 143, 143, 143, 163,
    188, 162, 162, 187, 162, 162, 162, 208, 208, 208, 208, 208, 208, 186, 185,
    166, 156, 155, 163, 163, 154, 163, 163, 163, 164, 164, 164, 164, 167, 164,
    164, 164, 164, 164, 166, 166, 153, 166, 166, 166, 168, 152, 151, 150, 148,
    147, 164, 167, 167, 172, 167, 167, 167, 214, 214, 214, 146, 145, 164, 168,
    168, 144, 168, 168, 168, 141, 214, 140, 172, 172, 139, 172, 172, 172, 135,
    131, 127, 164, 164, 164, 164, 164, 164, 169, 169,

    169, 169, 125, 169, 169, 169, 169, 169, 169, 169, 169, 173, 123, 122, 214,
    214, 214, 174, 121, 119, 169, 169, 118, 177, 117, 215, 215, 215, 115, 114,
    173, 173, 169, 173, 173, 173, 174, 174, 215, 174, 174, 174, 177, 177, 113,
    177, 177, 177, 112, 108, 107, 169, 169, 169, 169, 169, 169, 170, 170, 170,
    170, 101, 170, 170, 170, 170, 170, 170, 170, 170, 178, 215, 215, 215, 100,
    89,  179, 87,  86,  170, 170, 70,  181, 271, 271, 271, 271, 271, 271, 178,
    178, 170, 178, 178, 178, 179, 179, 69,  179, 179,

    179, 181, 68,  65,  181, 181, 181, 63,  62,  61,  170, 170, 170, 170, 170,
    170, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171,
    171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171,
    171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171,
    171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171,
    175, 175, 175, 175, 57,  175, 175, 175, 175, 175, 175, 175, 175, 183, 55,
    46,  45,  44,  33,  184, 32,  31,  175, 175, 222,

    222, 222, 222, 222, 222, 222, 222, 183, 183, 175, 183, 183, 183, 184, 184,
    27,  184, 184, 184, 223, 223, 26,  25,  22,  7,   0,   0,   0,   175, 175,
    175, 175, 175, 175, 176, 176, 176, 176, 0,   176, 176, 176, 176, 176, 176,
    176, 176, 227, 227, 227, 227, 227, 227, 227, 227, 228, 176, 176, 0,   0,
    0,   229, 0,   0,   0,   223, 223, 223, 176, 0,   0,   0,   0,   0,   228,
    230, 0,   228, 228, 228, 229, 229, 232, 229, 229, 229, 0,   176, 176, 176,
    176, 176, 176, 233, 230, 230, 0,   230, 230, 230,

    236, 232, 232, 0,   232, 232, 232, 237, 0,   0,   0,   0,   233, 233, 238,
    233, 233, 233, 0,   236, 236, 0,   236, 236, 236, 0,   237, 237, 0,   237,
    237, 237, 0,   238, 238, 241, 238, 238, 238, 239, 239, 239, 239, 0,   239,
    239, 239, 239, 239, 239, 239, 239, 242, 0,   241, 241, 0,   241, 241, 241,
    243, 239, 239, 0,   0,   0,   245, 0,   0,   0,   0,   242, 242, 239, 242,
    242, 242, 0,   0,   243, 243, 0,   243, 243, 243, 245, 245, 0,   245, 245,
    245, 0,   239, 239, 239, 239, 239, 239, 240, 240,

    240, 240, 247, 240, 240, 240, 240, 240, 240, 240, 240, 246, 0,   0,   0,
    0,   248, 249, 0,   0,   240, 240, 0,   0,   247, 0,   0,   0,   0,   0,
    246, 246, 240, 246, 246, 246, 249, 249, 248, 249, 249, 249, 0,   247, 250,
    0,   247, 247, 247, 0,   251, 240, 240, 240, 240, 240, 240, 248, 253, 0,
    248, 248, 248, 250, 250, 254, 250, 250, 250, 251, 251, 256, 251, 251, 251,
    0,   0,   253, 253, 278, 253, 253, 253, 0,   254, 254, 279, 254, 254, 254,
    256, 256, 281, 256, 256, 256, 0,   0,   278, 278,

    282, 278, 278, 278, 0,   279, 279, 285, 279, 279, 279, 281, 281, 286, 281,
    281, 281, 0,   0,   282, 282, 287, 282, 282, 282, 0,   285, 285, 289, 285,
    285, 285, 286, 286, 290, 286, 286, 286, 292, 0,   287, 287, 291, 287, 287,
    287, 0,   289, 289, 293, 289, 289, 289, 290, 290, 0,   290, 290, 290, 0,
    292, 291, 291, 0,   291, 291, 291, 294, 293, 293, 0,   293, 293, 293, 295,
    0,   0,   0,   0,   292, 306, 0,   292, 292, 292, 0,   294, 294, 308, 294,
    294, 294, 0,   295, 295, 309, 295, 295, 295, 306,

    306, 310, 306, 306, 306, 0,   0,   308, 308, 311, 308, 308, 308, 0,   309,
    309, 319, 309, 309, 309, 310, 310, 0,   310, 310, 310, 0,   0,   311, 311,
    0,   311, 311, 311, 0,   319, 319, 0,   319, 319, 319, 330, 330, 330, 330,
    330, 330, 330, 330, 331, 331, 331, 331, 331, 331, 331, 331, 332, 332, 332,
    332, 332, 332, 333, 333, 333, 0,   0,   333, 334, 334, 334, 0,   0,   334,
    335, 335, 335, 336, 336, 336, 336, 336, 336, 336, 336, 337, 337, 337, 337,
    337, 337, 337, 338, 338, 338, 338, 338, 339, 339,

    339, 339, 339, 339, 339, 339, 340, 340, 340, 340, 340, 340, 341, 341, 341,
    0,   0,   341, 342, 342, 342, 342, 342, 342, 343, 343, 343, 343, 343, 343,
    343, 343, 344, 344, 344, 344, 344, 344, 344, 344, 345, 345, 345, 346, 346,
    346, 347, 347, 348, 348, 348, 348, 348, 348, 349, 349, 349, 349, 349, 349,
    349, 349, 350, 350, 350, 350, 350, 350, 350, 350, 351, 351, 351, 352, 352,
    352, 353, 353, 353, 353, 353, 353, 353, 353, 329, 329, 329, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329,

    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329,
    329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329, 329};

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"

#line 4 "lex.l"
/** \file  */
#include "byte.h"
#include "char.h"

#include "parse.tab.h"

char *real;
char imag_sgn;

#line 955 "lex.yy.c"

#define INITIAL 0
#define STR 1
#define BV 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals(void);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy(void);

int yyget_debug(void);

void yyset_debug(int debug_flag);

YY_EXTRA_TYPE yyget_extra(void);

void yyset_extra(YY_EXTRA_TYPE user_defined);

FILE *yyget_in(void);

void yyset_in(FILE *_in_str);

FILE *yyget_out(void);

void yyset_out(FILE *_out_str);

yy_size_t yyget_leng(void);

char *yyget_text(void);

int yyget_lineno(void);

void yyset_lineno(int _line_number);

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap(void);
#else
extern int yywrap(void);
#endif
#endif

#ifndef YY_NO_UNPUT

static void yyunput(int c, char *buf_ptr);

#endif

#ifndef yytext_ptr
static void yy_flex_strncpy(char *, yyconst char *, int);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(yyconst char *);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput(void);
#else
static int input(void);
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO                                                                   \
  do {                                                                         \
    if (fwrite(yytext, yyleng, 1, yyout)) {                                    \
    }                                                                          \
  } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)                                        \
  if (YY_CURRENT_BUFFER_LVALUE->yy_is_interactive) {                           \
    int c = '*';                                                               \
    size_t n;                                                                  \
    for (n = 0; n < max_size && (c = getc(yyin)) != EOF && c != '\n'; ++n)     \
      buf[n] = (char)c;                                                        \
    if (c == '\n')                                                             \
      buf[n++] = (char)c;                                                      \
    if (c == EOF && ferror(yyin))                                              \
      YY_FATAL_ERROR("input in flex scanner failed");                          \
    result = n;                                                                \
  } else {                                                                     \
    errno = 0;                                                                 \
    while ((result = fread(buf, 1, max_size, yyin)) == 0 && ferror(yyin)) {    \
      if (errno != EINTR) {                                                    \
        YY_FATAL_ERROR("input in flex scanner failed");                        \
        break;                                                                 \
      }                                                                        \
      errno = 0;                                                               \
      clearerr(yyin);                                                          \
    }                                                                          \
  }

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex(void);

#define YY_DECL int yylex(void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/ break;
#endif

#define YY_RULE_SETUP YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL {
  yy_state_type yy_current_state;
  char *yy_cp, *yy_bp;
  int yy_act;

  if (!(yy_init)) {
    (yy_init) = 1;

#ifdef YY_USER_INIT
    YY_USER_INIT;
#endif

    if (!(yy_start))
      (yy_start) = 1; /* first start state */

    if (!yyin)
      yyin = stdin;

    if (!yyout)
      yyout = stdout;

    if (!YY_CURRENT_BUFFER) {
      yyensure_buffer_stack();
      YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);
    }

    yy_load_buffer_state();
  }

  {
#line 37 "lex.l"

#line 1178 "lex.yy.c"

    while (/*CONSTCOND*/ 1) /* loops until end-of-file is reached */
    {
      yy_cp = (yy_c_buf_p);

      /* Support of yytext. */
      *yy_cp = (yy_hold_char);

      /* yy_bp points to the position in yy_ch_buf of the start of
       * the current run.
       */
      yy_bp = yy_cp;

      yy_current_state = (yy_start);
    yy_match:
      do {
        YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
        if (yy_accept[yy_current_state]) {
          (yy_last_accepting_state) = yy_current_state;
          (yy_last_accepting_cpos) = yy_cp;
        }
        while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
          yy_current_state = (int)yy_def[yy_current_state];
          if (yy_current_state >= 330)
            yy_c = yy_meta[(unsigned int)yy_c];
        }
        yy_current_state =
            yy_nxt[yy_base[yy_current_state] + (unsigned int)yy_c];
        ++yy_cp;
      } while (yy_base[yy_current_state] != 1585);

    yy_find_action:
      yy_act = yy_accept[yy_current_state];
      if (yy_act == 0) { /* have to back up */
        yy_cp = (yy_last_accepting_cpos);
        yy_current_state = (yy_last_accepting_state);
        yy_act = yy_accept[yy_current_state];
      }

      YY_DO_BEFORE_ACTION;

    do_action: /* This label is used only to access EOF actions. */

      switch (yy_act) { /* beginning of action switch */
      case 0:           /* must back up */
        /* undo the effects of YY_DO_BEFORE_ACTION */
        *yy_cp = (yy_hold_char);
        yy_cp = (yy_last_accepting_cpos);
        yy_current_state = (yy_last_accepting_state);
        goto yy_find_action;

      case 1:
        /* rule 1 can match eol */
        YY_RULE_SETUP
#line 39 "lex.l"
        {
        }
        YY_BREAK
      /* atmosphere  */
      case 2:
        /* rule 2 can match eol */
        YY_RULE_SETUP
#line 42 "lex.l"
        {
        }
        YY_BREAK
      case 3:
        /* rule 3 can match eol */
        YY_RULE_SETUP
#line 43 "lex.l"
        {
        }
        YY_BREAK
      case 4:
        /* rule 4 can match eol */
        YY_RULE_SETUP
#line 44 "lex.l"
        {
        }
        YY_BREAK
      case 5:
        YY_RULE_SETUP
#line 45 "lex.l"
        {
          return LEX_SHARP_SEMICOLON;
        }
        YY_BREAK
      case 6:
#line 48 "lex.l"
      case 7:
#line 49 "lex.l"
      case 8:
#line 50 "lex.l"
      case 9:
        YY_RULE_SETUP
#line 50 "lex.l"
        {
          return yytext[0];
        }
        YY_BREAK
      case 10:
        YY_RULE_SETUP
#line 54 "lex.l"
        {
          return LEX_SHARP_OP;
        }
        YY_BREAK
      case 11:
        YY_RULE_SETUP
#line 55 "lex.l"
        {
          BEGIN BV;
          return LEX_SHARP_U_EIGHT_OP;
        }
        YY_BREAK
      case 12:
        YY_RULE_SETUP
#line 57 "lex.l"
        {
          yylval.o = symbol_new(yytext);
          return LEX_SYMBOL;
        }
        YY_BREAK
      case 13:
        YY_RULE_SETUP
#line 60 "lex.l"
        {
          yytext[yyleng - 1] = '\0';
          yytext++;
          yylval.o = symbol_new(yytext);
          return LEX_SYMBOL;
        }
        YY_BREAK
      case 14:
        YY_RULE_SETUP
#line 65 "lex.l"
        {
          yylval.o = symbol_new(yytext);
          return LEX_SYMBOL;
        }
        YY_BREAK
      case 15:
        YY_RULE_SETUP
#line 68 "lex.l"
        {
          yytext[yyleng - 1] = '\0';
          yytext++;
          yylval.o = symbol_new(yytext);
          return LEX_SYMBOL;
        }
        YY_BREAK
      case 16:
        /* rule 16 can match eol */
        YY_RULE_SETUP
#line 73 "lex.l"
        {
          yytext[yyleng - 1] = '\0';
          yytext++;
          yylval.o = symbol_vertical_new(yytext);
          return LEX_SYMBOL;
        }
        YY_BREAK
      case 17:
        YY_RULE_SETUP
#line 78 "lex.l"
        {
          yylval.o = boolean_true;
          return LEX_BOOLEAN;
        }
        YY_BREAK
      case 18:
        YY_RULE_SETUP
#line 79 "lex.l"
        {
          ;
          yylval.o = boolean_false;
          return LEX_BOOLEAN;
        }
        YY_BREAK
      case 19:
        /* rule 19 can match eol */
        YY_RULE_SETUP
#line 81 "lex.l"
        {
          yytext += 2;
          yylval.o = char_new(yytext);
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 20:
        YY_RULE_SETUP
#line 85 "lex.l"
        {
          yylval.o = char_new("\x07");
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 21:
        YY_RULE_SETUP
#line 88 "lex.l"
        {
          yylval.o = char_new("\x08");
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 22:
        YY_RULE_SETUP
#line 91 "lex.l"
        {
          yylval.o = char_new("\x7f");
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 23:
        YY_RULE_SETUP
#line 94 "lex.l"
        {
          yylval.o = char_new("\x1b");
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 24:
        YY_RULE_SETUP
#line 97 "lex.l"
        {
          yylval.o = char_new("\xa");
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 25:
        YY_RULE_SETUP
#line 100 "lex.l"
        {
          yylval.o = char_new("\x00");
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 26:
        YY_RULE_SETUP
#line 103 "lex.l"
        {
          yylval.o = char_new("\r");
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 27:
        YY_RULE_SETUP
#line 106 "lex.l"
        {
          yylval.o = char_new(" ");
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 28:
        YY_RULE_SETUP
#line 109 "lex.l"
        {
          yylval.o = char_new("\t");
          return LEX_CHARACTER;
        }
        YY_BREAK
      case 29:
        YY_RULE_SETUP
#line 112 "lex.l"
        {
          yytext += 3;
          char *endptr = NULL;
          uintmax_t ui = strtoumax(yytext, &endptr, 16);
          if (ui == UINTMAX_MAX || ui > 0xffffffff) {
            /* yyerror("unicode: overflow"); */
          } else {
            yylval.o = (Object){.type = CHAR, .ch = ui};
            return LEX_CHARACTER;
          }
        }
        YY_BREAK
      case 30:
        YY_RULE_SETUP
#line 123 "lex.l"
        {
          BEGIN STR;
          return '"';
        }
        YY_BREAK
      case 31:
        /* rule 31 can match eol */
        YY_RULE_SETUP
#line 127 "lex.l"
        {
          yylval.o = char_new(yytext);
          return LEX_STRING_ELEMENT;
        }
        YY_BREAK
      case 32:
        YY_RULE_SETUP
#line 131 "lex.l"
        {
          yylval.o = (Object){.type = CHAR, .ch = 0x07};
          return LEX_STRING_ELEMENT;
        }
        YY_BREAK
      case 33:
        YY_RULE_SETUP
#line 132 "lex.l"
        {
          yylval.o = (Object){.type = CHAR, .ch = 0x08};
          return LEX_STRING_ELEMENT;
        }
        YY_BREAK
      case 34:
        YY_RULE_SETUP
#line 133 "lex.l"
        {
          yylval.o = (Object){.type = CHAR, .ch = 0x09};
          return LEX_STRING_ELEMENT;
        }
        YY_BREAK
      case 35:
        YY_RULE_SETUP
#line 134 "lex.l"
        {
          yylval.o = (Object){.type = CHAR, .ch = 0x0a};
          return LEX_STRING_ELEMENT;
        }
        YY_BREAK
      case 36:
        YY_RULE_SETUP
#line 135 "lex.l"
        {
          yylval.o = (Object){.type = CHAR, .ch = 0x0d};
          return LEX_STRING_ELEMENT;
        }
        YY_BREAK
      case 37:
        YY_RULE_SETUP
#line 136 "lex.l"
        {
          yylval.o = (Object){.type = CHAR, .ch = 0x22};
          return LEX_STRING_ELEMENT;
        }
        YY_BREAK
      case 38:
        YY_RULE_SETUP
#line 137 "lex.l"
        {
          yylval.o = (Object){.type = CHAR, .ch = 0x5c};
          return LEX_STRING_ELEMENT;
        }
        YY_BREAK
      case 39:
        /* rule 39 can match eol */
        YY_RULE_SETUP
#line 138 "lex.l"
        {
        }
        YY_BREAK
      case 40:
        YY_RULE_SETUP
#line 141 "lex.l"
        {
          yytext[yyleng - 1] = '\0';
          yytext += 2;
          char *endptr = NULL;
          uintmax_t ui = strtoumax(yytext, &endptr, 16);
          if (ui == UINTMAX_MAX || ui > 0xffffffff) {
            /* yyerror("unicode: overflow"); */
          } else {
            yylval.o = (Object){.type = CHAR, .ch = ui};
            return LEX_STRING_ELEMENT;
          }
        }
        YY_BREAK
      case 41:
        YY_RULE_SETUP
#line 153 "lex.l"
        {
          BEGIN INITIAL;
          return '"';
        }
        YY_BREAK
      case 42:
        YY_RULE_SETUP
#line 157 "lex.l"
        {
          yytext += 2;
          yylval.o = rational_new(yytext, 2);
          return LEX_EXACT;
        }
        YY_BREAK
      case 43:
        YY_RULE_SETUP
#line 162 "lex.l"
        {
          yytext += 2;
          yylval.o = rational_new(yytext, 8);
          return LEX_EXACT;
        }
        YY_BREAK
      case 44:
        YY_RULE_SETUP
#line 167 "lex.l"
        {
          if (yytext[0] == '#') {
            yytext += 2;
          }
          yylval.o = rational_new(yytext, 10);
          return LEX_EXACT;
        }
        YY_BREAK
      case 45:
        YY_RULE_SETUP
#line 175 "lex.l"
        {
          yytext += 2;
          yylval.o = rational_new(yytext, 16);
          return LEX_EXACT;
        }
        YY_BREAK
      case 46:
#line 181 "lex.l"
      case 47:
#line 182 "lex.l"
      case 48:
#line 183 "lex.l"
      case 49:
#line 184 "lex.l"
      case 50:
        YY_RULE_SETUP
#line 184 "lex.l"
        {
          yylval.o = byte_new(yytext);
          return LEX_BYTE;
        }
        YY_BREAK
      case 51:
        YY_RULE_SETUP
#line 185 "lex.l"
        {
          BEGIN INITIAL;
          return yytext[0];
        }
        YY_BREAK
      case YY_STATE_EOF(INITIAL):
      case YY_STATE_EOF(STR):
      case YY_STATE_EOF(BV):
#line 187 "lex.l"
      {
        yylval.o = (Object){.type = EOF_OBJ};
        return LEX_EOF;
      }
        YY_BREAK
      case 52:
        YY_RULE_SETUP
#line 192 "lex.l"
        {
          printf("lex: lineno: %d ??? '%c' '%x' '%d' \n", yylineno, yytext[0],
                 yytext[0], yytext[0]);
        }
        YY_BREAK
      case 53:
        YY_RULE_SETUP
#line 196 "lex.l"
        ECHO;
        YY_BREAK
#line 1589 "lex.yy.c"

      case YY_END_OF_BUFFER: {
        /* Amount of text matched not including the EOB char. */
        int yy_amount_of_matched_text = (int)(yy_cp - (yytext_ptr)) - 1;

        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = (yy_hold_char);
        YY_RESTORE_YY_MORE_OFFSET

        if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW) {
          /* We're scanning a new file or input source.  It's
           * possible that this happened because the user
           * just pointed yyin at a new source and called
           * yylex().  If so, then we have to assure
           * consistency between YY_CURRENT_BUFFER and our
           * globals.  Here is the right place to do so, because
           * this is the first action (other than possibly a
           * back-up) that will match for the new input source.
           */
          (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
          YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
          YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
        }

        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state).  Contrast this with the test
         * in input().
         */
        if ((yy_c_buf_p) <=
            &YY_CURRENT_BUFFER_LVALUE
                 ->yy_ch_buf[(yy_n_chars)]) { /* This was really a NUL. */
          yy_state_type yy_next_state;

          (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

          yy_current_state = yy_get_previous_state();

          /* Okay, we're now positioned to make the NUL
           * transition.  We couldn't have
           * yy_get_previous_state() go ahead and do it
           * for us because it doesn't know how to deal
           * with the possibility of jamming (and we don't
           * want to build jamming into it because then it
           * will run more slowly).
           */

          yy_next_state = yy_try_NUL_trans(yy_current_state);

          yy_bp = (yytext_ptr) + YY_MORE_ADJ;

          if (yy_next_state) {
            /* Consume the NUL. */
            yy_cp = ++(yy_c_buf_p);
            yy_current_state = yy_next_state;
            goto yy_match;
          }

          else {
            yy_cp = (yy_c_buf_p);
            goto yy_find_action;
          }
        }

        else
          switch (yy_get_next_buffer()) {
          case EOB_ACT_END_OF_FILE: {
            (yy_did_buffer_switch_on_eof) = 0;

            if (yywrap()) {
              /* Note: because we've taken care in
               * yy_get_next_buffer() to have set up
               * yytext, we can now set up
               * yy_c_buf_p so that if some total
               * hoser (like flex itself) wants to
               * call the scanner after we return the
               * YY_NULL, it'll still work - another
               * YY_NULL will get returned.
               */
              (yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

              yy_act = YY_STATE_EOF(YY_START);
              goto do_action;
            }

            else {
              if (!(yy_did_buffer_switch_on_eof))
                YY_NEW_FILE;
            }
            break;
          }

          case EOB_ACT_CONTINUE_SCAN:
            (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state();

            yy_cp = (yy_c_buf_p);
            yy_bp = (yytext_ptr) + YY_MORE_ADJ;
            goto yy_match;

          case EOB_ACT_LAST_MATCH:
            (yy_c_buf_p) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

            yy_current_state = yy_get_previous_state();

            yy_cp = (yy_c_buf_p);
            yy_bp = (yytext_ptr) + YY_MORE_ADJ;
            goto yy_find_action;
          }
        break;
      }

      default:
        YY_FATAL_ERROR("fatal flex scanner internal error--no action found");
      } /* end of action switch */
    }   /* end of scanning one token */
  }     /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer(void) {
  char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
  char *source = (yytext_ptr);
  yy_size_t number_to_move, i;
  int ret_val;

  if ((yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1])
    YY_FATAL_ERROR("fatal flex scanner internal error--end of buffer missed");

  if (YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer ==
      0) { /* Don't try to fill the buffer, so this is an EOF. */
    if ((yy_c_buf_p) - (yytext_ptr)-YY_MORE_ADJ == 1) {
      /* We matched a single character, the EOB, so
       * treat this as a final EOF.
       */
      return EOB_ACT_END_OF_FILE;
    }

    else {
      /* We matched some text prior to the EOB, first
       * process it.
       */
      return EOB_ACT_LAST_MATCH;
    }
  }

  /* Try to read more data. */

  /* First move last chars to start of buffer. */
  number_to_move = (yy_size_t)((yy_c_buf_p) - (yytext_ptr)) - 1;

  for (i = 0; i < number_to_move; ++i)
    *(dest++) = *(source++);

  if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING)
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
    YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

  else {
    yy_size_t num_to_read =
        YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

    while (num_to_read <= 0) { /* Not enough room in the buffer - grow it. */

      /* just a shorter name for the current buffer */
      YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

      int yy_c_buf_p_offset = (int)((yy_c_buf_p)-b->yy_ch_buf);

      if (b->yy_is_our_buffer) {
        yy_size_t new_size = b->yy_buf_size * 2;

        if (new_size <= 0)
          b->yy_buf_size += b->yy_buf_size / 8;
        else
          b->yy_buf_size *= 2;

        b->yy_ch_buf = (char *)
            /* Include room in for 2 EOB chars. */
            yyrealloc((void *)b->yy_ch_buf, b->yy_buf_size + 2);
      } else
        /* Can't grow it, we don't own it. */
        b->yy_ch_buf = 0;

      if (!b->yy_ch_buf)
        YY_FATAL_ERROR("fatal error - scanner input buffer overflow");

      (yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

      num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;
    }

    if (num_to_read > YY_READ_BUF_SIZE)
      num_to_read = YY_READ_BUF_SIZE;

    /* Read in more data. */
    YY_INPUT((&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
             (yy_n_chars), num_to_read);

    YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
  }

  if ((yy_n_chars) == 0) {
    if (number_to_move == YY_MORE_ADJ) {
      ret_val = EOB_ACT_END_OF_FILE;
      yyrestart(yyin);
    }

    else {
      ret_val = EOB_ACT_LAST_MATCH;
      YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_EOF_PENDING;
    }
  }

  else
    ret_val = EOB_ACT_CONTINUE_SCAN;

  if ((yy_size_t)((yy_n_chars) + number_to_move) >
      YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
    /* Extend the array by 50%, plus the number we really need. */
    yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *)yyrealloc(
        (void *)YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, new_size);
    if (!YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
      YY_FATAL_ERROR("out of dynamic memory in yy_get_next_buffer()");
  }

  (yy_n_chars) += number_to_move;
  YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
  YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

  (yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

  return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state(void) {
  yy_state_type yy_current_state;
  char *yy_cp;

  yy_current_state = (yy_start);

  for (yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp) {
    YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
    if (yy_accept[yy_current_state]) {
      (yy_last_accepting_state) = yy_current_state;
      (yy_last_accepting_cpos) = yy_cp;
    }
    while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
      yy_current_state = (int)yy_def[yy_current_state];
      if (yy_current_state >= 330)
        yy_c = yy_meta[(unsigned int)yy_c];
    }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int)yy_c];
  }

  return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
static yy_state_type yy_try_NUL_trans(yy_state_type yy_current_state) {
  int yy_is_jam;
  char *yy_cp = (yy_c_buf_p);

  YY_CHAR yy_c = 1;
  if (yy_accept[yy_current_state]) {
    (yy_last_accepting_state) = yy_current_state;
    (yy_last_accepting_cpos) = yy_cp;
  }
  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
    yy_current_state = (int)yy_def[yy_current_state];
    if (yy_current_state >= 330)
      yy_c = yy_meta[(unsigned int)yy_c];
  }
  yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int)yy_c];
  yy_is_jam = (yy_current_state == 329);

  return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

static void yyunput(int c, char *yy_bp) {
  char *yy_cp;

  yy_cp = (yy_c_buf_p);

  /* undo effects of setting up yytext */
  *yy_cp = (yy_hold_char);

  if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf +
                  2) { /* need to shift things up to make room */
    /* +2 for EOB chars. */
    yy_size_t number_to_move = (yy_n_chars) + 2;
    char *dest = &YY_CURRENT_BUFFER_LVALUE
                      ->yy_ch_buf[YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
    char *source = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

    while (source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
      *--dest = *--source;

    yy_cp += (int)(dest - source);
    yy_bp += (int)(dest - source);
    YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) =
        YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

    if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2)
      YY_FATAL_ERROR("flex scanner push-back overflow");
  }

  *--yy_cp = (char)c;

  (yytext_ptr) = yy_bp;
  (yy_hold_char) = *yy_cp;
  (yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput(void)
#else
static int input(void)
#endif

{
  int c;

  *(yy_c_buf_p) = (yy_hold_char);

  if (*(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR) {
    /* yy_c_buf_p now points to the character we want to return.
     * If this occurs *before* the EOB characters, then it's a
     * valid NUL; if not, then we've hit the end of the buffer.
     */
    if ((yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)])
      /* This was really a NUL. */
      *(yy_c_buf_p) = '\0';

    else { /* need more input */
      yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
      ++(yy_c_buf_p);

      switch (yy_get_next_buffer()) {
      case EOB_ACT_LAST_MATCH:
        /* This happens because yy_g_n_b()
         * sees that we've accumulated a
         * token and flags that we need to
         * try matching the token before
         * proceeding.  But for input(),
         * there's no matching to consider.
         * So convert the EOB_ACT_LAST_MATCH
         * to EOB_ACT_END_OF_FILE.
         */

        /* Reset buffer status. */
        yyrestart(yyin);

      /*FALLTHROUGH*/

      case EOB_ACT_END_OF_FILE: {
        if (yywrap())
          return EOF;

        if (!(yy_did_buffer_switch_on_eof))
          YY_NEW_FILE;
#ifdef __cplusplus
        return yyinput();
#else
        return input();
#endif
      }

      case EOB_ACT_CONTINUE_SCAN:
        (yy_c_buf_p) = (yytext_ptr) + offset;
        break;
      }
    }
  }

  c = *(unsigned char *)(yy_c_buf_p); /* cast for 8-bit char's */
  *(yy_c_buf_p) = '\0';               /* preserve yytext */
  (yy_hold_char) = *++(yy_c_buf_p);

  return c;
}
#endif /* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyrestart(FILE *input_file) {

  if (!YY_CURRENT_BUFFER) {
    yyensure_buffer_stack();
    YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);
  }

  yy_init_buffer(YY_CURRENT_BUFFER, input_file);
  yy_load_buffer_state();
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer) {

  /* TODO. We should be able to replace this entire function body
   * with
   *		yypop_buffer_state();
   *		yypush_buffer_state(new_buffer);
*/
  yyensure_buffer_stack();
  if (YY_CURRENT_BUFFER == new_buffer)
    return;

  if (YY_CURRENT_BUFFER) {
    /* Flush out information for old buffer. */
    *(yy_c_buf_p) = (yy_hold_char);
    YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
    YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
  }

  YY_CURRENT_BUFFER_LVALUE = new_buffer;
  yy_load_buffer_state();

  /* We don't actually know whether we did this switch during
   * EOF (yywrap()) processing, but the only time this flag
   * is looked at is after yywrap() is called, so it's safe
   * to go ahead and always set it.
   */
  (yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state(void) {
  (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
  (yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
  yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
  (yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c
 * YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
YY_BUFFER_STATE yy_create_buffer(FILE *file, int size) {
  YY_BUFFER_STATE b;

  b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

  b->yy_buf_size = (yy_size_t)size;

  /* yy_ch_buf has to be 2 characters longer than the size given because
   * we need to put in 2 end-of-buffer characters.
   */
  b->yy_ch_buf = (char *)yyalloc(b->yy_buf_size + 2);
  if (!b->yy_ch_buf)
    YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

  b->yy_is_our_buffer = 1;

  yy_init_buffer(b, file);

  return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */
void yy_delete_buffer(YY_BUFFER_STATE b) {

  if (!b)
    return;

  if (b == YY_CURRENT_BUFFER) /* Not sure if we should pop here. */
    YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE)0;

  if (b->yy_is_our_buffer)
    yyfree((void *)b->yy_ch_buf);

  yyfree((void *)b);
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
static void yy_init_buffer(YY_BUFFER_STATE b, FILE *file)

{
  int oerrno = errno;

  yy_flush_buffer(b);

  b->yy_input_file = file;
  b->yy_fill_buffer = 1;

  /* If b is the current buffer, then yy_init_buffer was _probably_
   * called from yyrestart() or through yy_get_next_buffer.
   * In that case, we don't want to reset the lineno or column.
   */
  if (b != YY_CURRENT_BUFFER) {
    b->yy_bs_lineno = 1;
    b->yy_bs_column = 0;
  }

  b->yy_is_interactive = file ? (isatty(fileno(file)) > 0) : 0;

  errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
void yy_flush_buffer(YY_BUFFER_STATE b) {
  if (!b)
    return;

  b->yy_n_chars = 0;

  /* We always need two end-of-buffer characters.  The first causes
   * a transition to the end-of-buffer state.  The second causes
   * a jam in that state.
   */
  b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
  b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

  b->yy_buf_pos = &b->yy_ch_buf[0];

  b->yy_at_bol = 1;
  b->yy_buffer_status = YY_BUFFER_NEW;

  if (b == YY_CURRENT_BUFFER)
    yy_load_buffer_state();
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
void yypush_buffer_state(YY_BUFFER_STATE new_buffer) {
  if (new_buffer == NULL)
    return;

  yyensure_buffer_stack();

  /* This block is copied from yy_switch_to_buffer. */
  if (YY_CURRENT_BUFFER) {
    /* Flush out information for old buffer. */
    *(yy_c_buf_p) = (yy_hold_char);
    YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
    YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
  }

  /* Only push if top exists. Otherwise, replace top. */
  if (YY_CURRENT_BUFFER)
    (yy_buffer_stack_top)++;
  YY_CURRENT_BUFFER_LVALUE = new_buffer;

  /* copied from yy_switch_to_buffer. */
  yy_load_buffer_state();
  (yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
void yypop_buffer_state(void) {
  if (!YY_CURRENT_BUFFER)
    return;

  yy_delete_buffer(YY_CURRENT_BUFFER);
  YY_CURRENT_BUFFER_LVALUE = NULL;
  if ((yy_buffer_stack_top) > 0)
    --(yy_buffer_stack_top);

  if (YY_CURRENT_BUFFER) {
    yy_load_buffer_state();
    (yy_did_buffer_switch_on_eof) = 1;
  }
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack(void) {
  yy_size_t num_to_alloc;

  if (!(yy_buffer_stack)) {

    /* First allocation is just for 2 elements, since we don't know if this
     * scanner will even need a stack. We use 2 instead of 1 to avoid an
     * immediate realloc on the next call.
*/
    num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
    (yy_buffer_stack) = (struct yy_buffer_state **)yyalloc(
        num_to_alloc * sizeof(struct yy_buffer_state *));
    if (!(yy_buffer_stack))
      YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

    memset((yy_buffer_stack), 0,
           num_to_alloc * sizeof(struct yy_buffer_state *));

    (yy_buffer_stack_max) = num_to_alloc;
    (yy_buffer_stack_top) = 0;
    return;
  }

  if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {

    /* Increase the buffer to prepare for a possible push. */
    yy_size_t grow_size = 8 /* arbitrary grow size */;

    num_to_alloc = (yy_buffer_stack_max) + grow_size;
    (yy_buffer_stack) = (struct yy_buffer_state **)yyrealloc(
        (yy_buffer_stack), num_to_alloc * sizeof(struct yy_buffer_state *));
    if (!(yy_buffer_stack))
      YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

    /* zero only the new slots.*/
    memset((yy_buffer_stack) + (yy_buffer_stack_max), 0,
           grow_size * sizeof(struct yy_buffer_state *));
    (yy_buffer_stack_max) = num_to_alloc;
  }
}

/** Setup the input buffer state to scan directly from a user-specified
 * character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer(char *base, yy_size_t size) {
  YY_BUFFER_STATE b;

  if (size < 2 || base[size - 2] != YY_END_OF_BUFFER_CHAR ||
      base[size - 1] != YY_END_OF_BUFFER_CHAR)
    /* They forgot to leave room for the EOB's. */
    return 0;

  b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR("out of dynamic memory in yy_scan_buffer()");

  b->yy_buf_size = size - 2; /* "- 2" to take care of EOB's */
  b->yy_buf_pos = b->yy_ch_buf = base;
  b->yy_is_our_buffer = 0;
  b->yy_input_file = 0;
  b->yy_n_chars = b->yy_buf_size;
  b->yy_is_interactive = 0;
  b->yy_at_bol = 1;
  b->yy_fill_buffer = 0;
  b->yy_buffer_status = YY_BUFFER_NEW;

  yy_switch_to_buffer(b);

  return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 *
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string(yyconst char *yystr) {

  return yy_scan_bytes(yystr, strlen(yystr));
}

/** Setup the input buffer state to scan the given bytes. The next call to
 * yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes(yyconst char *yybytes, yy_size_t _yybytes_len) {
  YY_BUFFER_STATE b;
  char *buf;
  yy_size_t n;
  yy_size_t i;

  /* Get memory for full buffer, including space for trailing EOB's. */
  n = _yybytes_len + 2;
  buf = (char *)yyalloc(n);
  if (!buf)
    YY_FATAL_ERROR("out of dynamic memory in yy_scan_bytes()");

  for (i = 0; i < _yybytes_len; ++i)
    buf[i] = yybytes[i];

  buf[_yybytes_len] = buf[_yybytes_len + 1] = YY_END_OF_BUFFER_CHAR;

  b = yy_scan_buffer(buf, n);
  if (!b)
    YY_FATAL_ERROR("bad buffer in yy_scan_bytes()");

  /* It's okay to grow etc. this buffer, and we should throw it
   * away when we're done.
   */
  b->yy_is_our_buffer = 1;

  return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error(yyconst char *msg) {
  (void)fprintf(stderr, "%s\n", msg);
  exit(YY_EXIT_FAILURE);
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n)                                                              \
  do {                                                                         \
    /* Undo effects of setting up yytext. */                                   \
    int yyless_macro_arg = (n);                                                \
    YY_LESS_LINENO(yyless_macro_arg);                                          \
    yytext[yyleng] = (yy_hold_char);                                           \
    (yy_c_buf_p) = yytext + yyless_macro_arg;                                  \
    (yy_hold_char) = *(yy_c_buf_p);                                            \
    *(yy_c_buf_p) = '\0';                                                      \
    yyleng = yyless_macro_arg;                                                 \
  } while (0)

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 *
 */
int yyget_lineno(void) { return yylineno; }

/** Get the input stream.
 *
 */
FILE *yyget_in(void) { return yyin; }

/** Get the output stream.
 *
 */
FILE *yyget_out(void) { return yyout; }

/** Get the length of the current token.
 *
 */
yy_size_t yyget_leng(void) { return yyleng; }

/** Get the current token.
 *
 */

char *yyget_text(void) { return yytext; }

/** Set the current line number.
 * @param _line_number line number
 *
 */
void yyset_lineno(int _line_number) { yylineno = _line_number; }

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 *
 * @see yy_switch_to_buffer
 */
void yyset_in(FILE *_in_str) { yyin = _in_str; }

void yyset_out(FILE *_out_str) { yyout = _out_str; }

int yyget_debug(void) { return yy_flex_debug; }

void yyset_debug(int _bdebug) { yy_flex_debug = _bdebug; }

static int yy_init_globals(void) {
  /* Initialization is the same as for the non-reentrant scanner.
*This function is called from yylex_destroy(), so don't allocate here.
*/

  (yy_buffer_stack) = 0;
  (yy_buffer_stack_top) = 0;
  (yy_buffer_stack_max) = 0;
  (yy_c_buf_p) = (char *)0;
  (yy_init) = 0;
  (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
  yyin = stdin;
  yyout = stdout;
#else
  yyin = (FILE *)0;
  yyout = (FILE *)0;
#endif

  /* For future reference: Set errno on error, since we are called by
   * yylex_init()
   */
  return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy(void) {

  /* Pop the buffer stack, destroying each element. */
  while (YY_CURRENT_BUFFER) {
    yy_delete_buffer(YY_CURRENT_BUFFER);
    YY_CURRENT_BUFFER_LVALUE = NULL;
    yypop_buffer_state();
  }

  /* Destroy the stack itself. */
  yyfree((yy_buffer_stack));
  (yy_buffer_stack) = NULL;

  /* Reset the globals. This is important in a non-reentrant scanner so the next
   * time
   * yylex() is called, initialization will occur. */
  yy_init_globals();

  return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy(char *s1, yyconst char *s2, int n) {

  int i;
  for (i = 0; i < n; ++i)
    s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(yyconst char *s) {
  int n;
  for (n = 0; s[n]; ++n)
    ;

  return n;
}
#endif

void *yyalloc(yy_size_t size) { return (void *)malloc(size); }

void *yyrealloc(void *ptr, yy_size_t size) {

  /* The cast to (char *) in the following accommodates both
   * implementations that use char* generic pointers, and those
   * that use void* generic pointers.  It works with the latter
   * because both ANSI C and C++ allow castless assignment from
   * any pointer type to void*, and deal with argument conversions
   * as though doing an assignment.
   */
  return (void *)realloc((char *)ptr, size);
}

void yyfree(void *ptr) {
  free((char *)ptr); /* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 196 "lex.l"

void yyerror(char *msg) {
  fprintf(stderr, "yyerror: '%s' '%s'\n", msg, yytext);
}

void f() {
  yyunput(10, "a");
  printf("%p\n", input);
}

extern Object input_obj;
Object c_str_to_datum(char const *s) {
  yy_scan_string(s);
  yyparse();
  return input_obj;
}
Object number_to_string(Object args) {
  Object o1 = carref(argl);
  char *s = NULL;
  if (o1.type == COMPLEX) {
    asprintf(&s, "%lf%f+lfi", creal(o1.z), cimag(o1.z));
    yy_scan_string(s);
    yyparse();
    free(s);
  } else if (o1.type == RATIONAL) {
    if (mpz_cmp_ui(mpq_denref(o1.rational), 1) == 0) {
      gmp_asprintf(&s, "\"%Zd\"", mpq_numref(o1.rational));
    } else {
      gmp_asprintf(&s, "\"%Qd\"", o1.rational);
    }
    yy_scan_string(s);
    yyparse();
    g_free(s);
  }
  return input_obj;
}

Object object_read(Object args) {
  Object o = carref(argl);
  FILE *t = cur_input;
  cur_input = o.port;
  yyrestart(cur_input);
  yyparse();
  cur_input = t;
  yyrestart(cur_input);
  return input_obj;
}
